# Generated by Django 4.1 on 2022-08-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ass', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='BODY',
            new_name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='pegzys pastries', max_length=255),
        ),
    ]
